apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifu-akri-adapter
  namespace: shifu-crd-system
spec:
  selector:
    matchLabels:
      app: shifu-akri-adapter
  template:
    metadata:
      labels:
        app: shifu-akri-adapter
    spec:
      serviceAccount: shifu-akri-sa
      containers:
      - name: shifu-akri-adapter
        image: edgenesis/shifu-akri-adapter:nightly
        resources: