apiVersion: v1
kind: ServiceAccount
metadata:
  name: shifu-akri-sa
  namespace: shifu-crd-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akri-shifu-controller-akri
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: akri-controller-role
subjects:
  - kind: ServiceAccount
    name: shifu-akri-sa
    namespace: shifu-crd-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akri-shifu-controller-shifu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shifu-crd-manager-role
subjects:
  - kind: ServiceAccount
    name: shifu-akri-sa
    namespace: shifu-crd-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akri-shifu-controller-action
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: shifu-akri-sa
    namespace: shifu-crd-system
